Restaurant_Management_System_Project_Django/Restaurant_Management_System_Project_Django/hotel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^menu/$', views.menu, name='menu'),
    url(r'^myorders/$', views.my_orders, name='my_orders'),
    
    url(r'^dashboard/admin/users/$', views.users_admin, name='users_admin'),
    url(r'^dashboard/admin/orders/$', views.orders_admin, name='orders_admin'),
    url(r'^dashboard/admin/foods/$', views.foods_admin, name='foods_admin'),
    url(r'^dashboard/admin/$', views.dashboard_admin, name='dashboard_admin'),
    url(r'^dashboard/admin/sales/$', views.sales_admin, name='sales_admin'),
    
    url(r'^dashboard/admin/users/add_user/$', views.add_user, name='add_user'),
    url(r'^dashboard/admin/foods/add_food/$', views.add_food, name='add_food'),
    url(r'^dashboard/admin/sales/add_sales/$', views.add_sales, name='add_sales'),
    url(r'^dashboard/admin/foods/editFood/(?P<foodID>\d+)/$', views.edit_food, name='edit_food'),
    url(r'^dashboard/admin/foods/foodDetails/(?P<foodID>\d+)/$', views.food_details, name='food_details'),
    url(r'^dashboard/admin/sales/editSale/(?P<saleID>\d+)/$', views.edit_sales, name='edit_sales'),
    
    url(r'^dashboard/admin/orders/confirm_order/(?P<orderID>\d+)/$', views.confirm_order, name='confirm_order'),
    url(r'^dashboard/admin/orders/confirm_delivery/(?P<orderID>\d+)/$', views.confirm_delivery, name='confirm_delivery'),
    
    url(r'^delete_item/(?P<ID>\d+)/$', views.delete_item, name='delete_item'),
    url(r'^add_deliveryBoy/(?P<orderID>\d+)/$', views.add_deliveryBoy, name='add_deliveryBoy'),
    url(r'^placeOrder/$', views.placeOrder, name='placeOrder'),
    url(r'^addTocart/(?P<foodID>\d+)/(?P<userID>\d+)/$', views.addTocart, name='addTocart'),

    url(r'^dashboard/delivery_boy/$', views.delivery_boy, name='delivery_boy'),
]

Restaurant_Management_System_Project_Django/Restaurant_Management_System_Project_Django/reflex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from hotel import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page':'/'}),
    url(r'^accounts/signup/$', views.signup, name='signup'),
    url(r'', include(('hotel.urls', 'hotel'), namespace='hotel')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Restaurant_Management_System_Project_Django/Restaurant_Management_System_Project_Django/hotel/forms.py
from django import forms
from .models import *

class SignUpForm(forms.ModelForm):
   
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Email', 'required':'true'}))
    firstname = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'First Name', 'required':'true'}))
    lastname = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name', 'required':'true'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password', 'required':'true'}))
    confirmpass = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Repeat Password', 'required':'true'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Address', 'required':'true'}))
    contact = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Contact', 'required':'true'}))

    class Meta:
        model = User
        fields = ['email','firstname', 'lastname', 'password', 'confirmpass']

    def clean(self):
        cleaned_data = super(SignUpForm, self).clean()
        password = cleaned_data.get('password')
        confirm_pass = cleaned_data.get('confirmpass')

        if password != confirm_pass:
            raise forms.ValidationError(
                "Password and confirm password does not match"
            )

Restaurant_Management_System_Project_Django/Restaurant_Management_System_Project_Django/hotel/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.utils import timezone
from reportlab.pdfgen import canvas
from .models import Customer, Comment, Order, Food, Data, Cart, OrderContent, Staff, DeliveryBoy
from .forms import SignUpForm

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.email = form.cleaned_data['email']
            user.first_name = form.cleaned_data['firstname']
            user.last_name = form.cleaned_data['lastname']
            user.email = form.cleaned_data['email']
            user.username = user.email.split('@')[0]
            user.set_password(form.cleaned_data['password'])
            user.save()
            address = form.cleaned_data['address']
            contact = form.cleaned_data['contact']
            customer = Customer.objects.create(customer=user, address=address, contact=contact)
            customer.save()
            return redirect('http://localhost:8000/accounts/login/')
        
    else:
        form = SignUpForm()
        
    return render(request, 'registration/signup.html', {'form': form})

@login_required
@staff_member_required
def dashboard_admin(request):
    comments = Comment.objects.count()
    orders = Order.objects.count()
    customers = Customer.objects.count()
    completed_orders = Order.objects.filter(payment_status="Completed")
    top_customers = Customer.objects.filter().order_by('-total_sale')
    latest_orders = Order.objects.filter().order_by('-order_timestamp')
    datas = Data.objects.filter().order_by('date')
    sales = 0
    for order in completed_orders:
        sales += order.total_amount

    context = {
        'comments':comments,
        'orders':orders,
        'customers':customers,
        'sales':sales,
        'top_customers': top_customers,
        'latest_orders':latest_orders,
        'datas':datas,
    }
    return render(request, 'admin_temp/index.html', context)

@login_required
@staff_member_required
def users_admin(request):
    customers = Customer.objects.filter()
    print(customers)
    return render(request, 'admin_temp/users.html', {'users':customers})

@login_required
@staff_member_required
def orders_admin(request):
    orders = Order.objects.filter()
    dBoys = Staff.objects.filter(role='Delivery Boy')
    print(dBoys)
    return render(request, 'admin_temp/orders.html', {'orders':orders, 'dBoys':dBoys})

@login_required
@staff_member_required
def foods_admin(request):
    foods = Food.objects.filter()
    return render(request, 'admin_temp/foods.html', {'foods':foods})

@login_required
@staff_member_required
def sales_admin(request):
    sales = Data.objects.filter()
    return render(request, 'admin_temp/sales.html', {'sales':sales})

def menu(request):
    cuisine = request.GET.get('cuisine')
    print(cuisine)
    if cuisine is not None:
        if ((cuisine == "Gujarati") or (cuisine == "Punjabi")):
            foods = Food.objects.filter(status="Enabled", course=cuisine)
        elif(cuisine == "south"):
            foods = Food.objects.filter(status="Enabled", course="South Indian")
        elif(cuisine == "fast"):
            foods = Food.objects.filter(course="Fast")
    else:
        foods = Food.objects.filter()
    return render(request, 'menu.html', {'foods':foods, 'cuisine':cuisine})


def index(request):
    food = Food.objects.filter().order_by('-num_order')
    return render(request, 'index.html', {'food':food})


@login_required
@staff_member_required
def confirm_order(request, orderID):
    order = Order.objects.get(id=orderID)
    order.confirmOrder()
    order.save()
    customerID = order.customer.id
    customer = Customer.objects.get(id=customerID)
    customer.total_sale += order.total_amount
    customer.orders += 1
    customer.save()
    return redirect('hotel:orders_admin')

@login_required
@staff_member_required
def confirm_delivery(request, orderID):
    to_email = []
    order = Order.objects.get(id=orderID)
    order.confirmDelivery()
    order.save()
    mail_subject = 'Order Delivered successfully'
    to = str(order.customer.customer.email)
    to_email.append(to)
    from_email = 'pradeepgangwar39@gmail.com'
    message = "Hi "+order.customer.customer.first_name+" Your order was delivered successfully. Please go to your dashboard to see your order history. <br> Your order id is "+orderID+". Share ypour feedback woth us."
    send_mail(
        mail_subject,
        message,
        from_email,
        to_email,
    )
    return redirect('hotel:orders_admin')

@login_required
@staff_member_required
def edit_food(request, foodID):
    food = Food.objects.filter(id=foodID)[0]
    if request.method == "POST":
        if request.POST['base_price'] != "":
            food.base_price = request.POST['base_price']
        
        if request.POST['discount'] != "":
            food.discount = request.POST['discount'] 
        
        food.sale_price = (100 - float(food.discount))*float(food.base_price)/100

        status = request.POST.get('disabled')
        print(status)
        if status == 'on':
            food.status = "Disabled"
        else:
            food.status = "Enabled"
        
        food.save()
    return redirect('hotel:foods_admin')

@login_required
@staff_member_required
def add_user(request):
    if request.method == "POST":
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        address = request.POST['address']
        contact = request.POST['contact']
        email = request.POST['email']
        password = request.POST['password']
        confirm_pass = request.POST['confirm_password']
        username = email.split('@')[0]
        
        if (first_name == "") or (last_name == "") or (address == "") or (contact == "") or (email == "") or (password == "") or (confirm_pass == ""):
            customers = Customer.objects.filter()
            error_msg = "Please enter valid details"
            return render(request, 'admin_temp/users.html', {'users': customers, 'error_msg': error_msg})

        if password == confirm_pass:
            user = User.objects.create(username=username, email=email, password=password, first_name=first_name, last_name=last_name)
            user.save()
            cust = Customer.objects.create(customer=user, address=address, contact=contact)
            cust.save()
            success_msg = "New user successfully created"
            customers = Customer.objects.filter()
            return render(request, 'admin_temp/users.html', {'users': customers, 'success_msg': success_msg})

    return redirect('hotel:users_admin')

@login_required
@staff_member_required
def add_food(request):
    if request.method == "POST":
        name = request.POST['name']
        course = request.POST['course']
        status = request.POST['status']
        content = request.POST['content']
        base_price = request.POST['base_price']
        discount = request.POST['discount']
        sale_price = (100 - float(discount)) * float(base_price) / 100
        image = request.FILES['image']
        fs = FileSystemStorage()
        filename = fs.save(image.name, image)

        if (name == "") or (course is None) or (status is None) or (content == "") or (base_price == "") or (discount == ""):
            foods = Food.objects.filter()
            error_msg = "Please enter valid details"
            return render(request, 'admin_temp/foods.html', {'foods': foods, 'error_msg': error_msg})

        food = Food.objects.create(name=name, course=course, status=status, content_description=content, base_price=base_price, discount=discount, sale_price=sale_price, image=filename)
        food.save()
        foods = Food.objects.filter()
        success_msg = "Please enter valid details"
        return render(request, 'admin_temp/foods.html', {'foods': foods, 'success_msg': success_msg})
    return redirect('hotel:foods_admin')

@login_required
@staff_member_required
def add_deliveryBoy(request, orderID):
    order = Order.objects.get(id=orderID)
    dName = request.POST['deliveryBoy']
    print(dName)
    user = User.objects.get(first_name=dName)
    deliveryBoy = Staff.objects.get(staff_id=user)
    order.delivery_boy = deliveryBoy
    order.save()
    return redirect('hotel:orders_admin')

@login_required
@staff_member_required
def add_sales(request):
    if request.method == "POST":
        date = request.POST['date']
        sales = request.POST['sales']
        expenses = request.POST['expenses']
        
        if (date is None) or (sales == "") or (expenses == ""):
            sales = Data.objects.filter()
            error_msg = "Please enter valid details"
            return render(request, 'admin_temp/sales.html', {'sales': sales, 'error_msg': error_msg})

        data = Data.objects.create(date=date, sales=sales, expenses=expenses)
        data.save()
        datas = Data.objects.filter()
        success_msg = "Sales data added successfully!"
        return render(request, 'admin_temp/sales.html', {'sales': datas, 'success_msg': success_msg})

    return redirect('hotel:foods_admin')

@login_required

Restaurant_Management_System_Project_Django/Restaurant_Management_System_Project_Django/hotel/templates/cart.html
{% load static %}

{% include "includes/landing_top.html" %}

{% load mathfilters %}

<body>
	<div  class="bg-img">
		<!-- banner -->
		{% include "includes/banner1.html" %}
		<!-- //banner -->
	</div>


        <div style="height:100px;"></div>
		
		<div class="container text-center">

			<div class="col-md-5 col-sm-12">
				<div class="bigcart"></div>
				<h1>Your shopping cart</h1>
			</div>
			
			<div class="col-md-7 col-sm-12 text-left">
				<ul>
					<li class="row list-inline columnCaptions">
						<span>QTY</span>
						<span>ITEM</span>
						<span>Price</span>
					</li>
                    {% for item in items %}
					<li class="row">
						<span class="quantity">{{item.quantity}}</span>
						<span class="itemName">{{item.food.name}}</span>
                        <span class="popbtn"><a class="arrow" id="{{item.id}}"></a></span>
                        <span class="price">₱ {{ item.food.sale_price|mul:item.quantity }}</span>
                    </li>
                    {% endfor %}
                    <li class="row totals">
						<span class="itemName">Total:</span>
						<span class="price">₱ {{total}}</span>
						<span class="order"> <a class="text-center" href="{% url 'hotel:placeOrder' %}">ORDER</a></span>
						<span class="order"> <a class="text-center" href="{% url 'hotel:menu' %}">Continue Shopping</a></span>
					</li>
				</ul>
			</div>

		</div>

		<!-- The popover content -->

		<div id="popover" style="display: none">
			<a><span class="glyphicon glyphicon-pencil"></span></a>
			<a id="remove"><span class="glyphicon glyphicon-remove"></span></a>
		</div>
		
		<!-- JavaScript includes -->

		<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script> 
		<script src="{% static 'js/bootstrap.js' %}"></script>
		<script src="{% static 'assets/js/customjs.js' %}"></script>

	</body>
</html>

Restaurant_Management_System_Project_Django/Restaurant_Management_System_Project_Django/hotel/templates/delivery_boy.html
{% load staticf %}
{% include "includes/base.html" %}
{% include "includes/navbarheader.html" %}
{% include "includes/navtop.html" %}
        </nav>
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="{% url 'hotel:dashboard_admin' %}">
                            <i class="fa fa-dashboard fa-fw"></i> Orders</a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Orders Information</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            List of all Orders
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Customer's Name</th>
                                        <th>Order Status</th>
                                        <th>Order Time</th>
                                        <th>Amount</th>
                                        <th>Payment Method</th>
                                        <th>Payment Status</th>
                                        <th>Confirm Payment</th>
                                        <th>Delivery Time</th>
                                        <th>Delivery Status</th>
                                        <th>Confirm Delivery</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td>{{order.id}}</td>
                                        <td>{{order.order.customer.customer.first_name}} {{order.order.customer.customer.last_name}}</td>
                                        <td>{% if order.order.if_cancelled == False %}
                                            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                            {% else %}
                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                            {% endif %}
                                        </td>
                                        <td>{{order.order.order_timestamp}}</td>
                                        <td>{{order.order.total_amount}}</td>
                                        <td>{{order.order.payment_method}}</td>
                                        <td>{% if order.payment_status == 'Completed' %}
                                            <span class="label label-success">Paid</span>
                                            {% else %}
                                            <span class="label label-danger">Pending</span>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a href="/confirm_order/{{order.id}}">
                                                <span class="input-group-btn">
                                                    <button class="btn btn-primary {%ifequal order.payment_status 'Completed'%}disabled{%endifequal%}" type="button">Paid</button>
                                                </span>
                                            </a>
                                        </td>
                                        <td>{{order.order.delivery_timestamp}}</td>
                                        <td>{% if order.order.delivery_status == 'Completed' %}
                                            <span class="label label-success">Delivered</span>
                                            {% else %}
                                            <span class="label label-danger">Pending</span>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a href="/confirm_delivery/{{order.id}}">
                                                <span class="input-group-btn">
                                                    <button class="btn btn-primary {%ifequal order.order.delivery_status 'Completed'%}disabled{%endifequal%}" type="button">Deliver</button>
                                                </span>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>

    <!-- DataTables JavaScript -->
    <script src="{% static '/vendor/datatables/js/jquery.dataTables.min.js'%}"></script>
    <script src="{% static '/vendor/datatables-plugins/dataTables.bootstrap.min.js'%}"></script>
    <script src="{% static '/vendor/datatables-responsive/dataTables.responsive.js'%}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>

    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'vendor/metisMenu/metisMenu.min.js'%}"></script>
    <script src="{% static 'dist/js/sb-admin-2.js'%}"></script>

</body>

</html>

Restaurant_Management_System_Project_Django/Restaurant_Management_System_Project_Django/hotel/templates/index.html
{% load static %}
{% load mathfilters %}
{% include "includes/landing_top.html" %}

<body>
	<script src="{% static 'js/jquery.vide.min.js' %}"></script>
	<div data-vide-bg="{% static 'video/bg.jpg' %}">
		<!-- banner -->
		{% include "includes/banner.html" %}
		<!-- //banner -->
	</div>
	<!-- special -->
	<div class="special">
		<div class="container">
			<div class="special-heading">
				<h3>Today Specials</h3>
			</div>
			<div class="special-grids">
			{% for f in food %}
					<div class="col-md-4 w3l-special-grid">
						<a href="{% url 'hotel:food_details' f.id %}">
							<div class="col-md-6 w3ls-special-img" style="background: url('/media/{{f.image}}') no-repeat -17px 0px; background-size: cover;">
								<div class="w3ls-special-text effect-1">
									<h4>{{f.name|truncatechars:11}}</h4>
								</div>
							</div>
						</a>

						<div class="col-md-6 agileits-special-info">
							<a href="{% url 'hotel:food_details' f.id %}"><h4>{{f.name|truncatechars:11}}</h4></a>
							<p>{{f.content_description|truncatechars:90}}</p>
						</div>
					</div>
			{% endfor %}
					<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //special -->
	<!-- features -->
	<div class="features">
		<div class="container">
			<div class="features-heading">
				<h3>Our Features</h3>
			</div>
			<div class="features-grids">
				<div class="col-md-4 features-left">
					<div class="features-left-info">
					</div>
				</div>
				<div class="col-md-8 features-right">
					<div class="features-right-info">
						<h4>The best restaurants in Manila keep with the cosmopolitan feel of this city, which blends a myriad of influences from all around the world, both in its history and its cuisine. Filipino food itself has already been shaped by aboriginal, Spanish, North American, Indonesian and Chinese cuisines, so you’re almost certain to find something to your taste in Manila.</h3>
					</div>
					<div class="features-right-grids">
						<div class="features-right-left">
							<div class="features-right-icon effect-2">
								<i class="fa fa-users" aria-hidden="true"></i>
							</div>
						</div>
						<div class="features-right-right">
							<p>Manila's dining scene includes an eclectic list of eateries which only have 1 point in common: they're mostly  are good. From upscale hotel’s restaurants to unpretentious budget cafés, and from local to international restaurants, the best places to eat in Manila are ready to serve you mouth-watering meals.</p>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="features-right-grids">
						<div class="features-right-left">
							<div class="features-right-icon effect-2">
								<i class="fa fa-asterisk" aria-hidden="true"></i>
							</div>
						</div>
						<div class="features-right-right">
							<p>Café Ilang-Ilang is a luxurious restaurant located in the historic Manila Hotel. It’s known for an extensive buffet selection that includes Japanese cuisine, Italian, Chinese, western, Asian, Filipino, and more. Their live cooking stations ensure that the food is well presented and of the highest quality. Sample their salad station, cold cuts and seafood station, burrito and shawarma station, and bread and cheese station. </p>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="features-right-grids">
						<div class="features-right-left">
							<div class="features-right-icon effect-2">
								<i class="fa fa-money" aria-hidden="true"></i>
							</div>
						</div>
						<div class="features-right-right">
							<p>Sky Deck View Bar is a stylish lounge and restaurant on the rooftop of The Bayleaf Intramuros. The venue is a stunning sundowner spot, offering views over Manila Bay. Food-wise, you can enjoy both Filipino and international cuisine, served in big portions at fair rates. A live music band is in charge of the entertainment on some nights, but the highlight of the Sky Deck remains the sunset over Manila.</p>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="features-right-grids">
						<div class="features-right-left">
							<div class="features-right-icon effect-2">
								<i class="fa fa-cog" aria-hidden="true"></i>
							</div>
						</div>
						<div class="features-right-right">
							<p>The Aristocrat is a long-established restaurant in the capital city of the Philippines, dating back to 1936. It's so successful that The Aristocrat has several branches throughout Manila. The restaurant serves a wide range of Filipino specialities at reasonable prices, though the house speciality of honey-cured chicken barbecue has been a favourite for generations. Drinks include beer, juices, soft drinks and mineral water.</p>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //features -->
	<!-- customer -->
	<div class="customer">
		<div class="container">
			<div class="customer-heading">
				<h3>What Our Customers are Saying</h3>
			</div>
			<div class="customer-heading-grids">
				<div class="col-md-4 customer-grid">
					<div class="customer-info">
						<p>Excellent Foods</p>
					</div>
					<div class="customer-img">
						
						<h5>Jude Angel Suares</h5>
					</div>
				</div>
				<div class="col-md-4 customer-grid">
					<div class="customer-info">
						<p>Its the best foods I eat ever had</p>
					</div>
					<div class="customer-img">
						
						<h5>Adrian Mercurio</h5>
					</div>
				</div>
				<div class="col-md-4 customer-grid">
					<div class="customer-info">
						<p>Super Tasty and Delicious</p>
					</div>
					<div class="customer-img">
						
						<h5>Niko Curaza</h5>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //customer -->
	{% include "includes/footer.html" %}

Restaurant_Management_System_Project_Django/Restaurant_Management_System_Project_Django/hotel/templates/menu.html
{% load static %}
{% load mathfilters %}
{% include "includes/landing_top.html" %}

<body>
	<script src="{% static 'js/jquery.vide.min.js' %}"></script>
	<div data-vide-bg="{% static 'video/bg.jpg' %}">
		<!-- banner -->
		{% include "includes/banner.html" %}
		<!-- //banner -->
	</div>
	<!-- menu -->
	<div class="menu">
		<div class="container">
			<div class="menu-heading">
				<h2>Our Menu</h2>
			</div>
			<div class="menu-top-grids">
				{% for food in foods %}
				{% if forloop.counter0|mod:4 == 1 %}
				<div class="w3ls-menu-grids">
				{% endif %}
					<div class="col-md-3 menu-grid">
						<div class="agile-menu-grid">
							<a href="{% url 'hotel:food_details' food.id %}">
								<img src="/media/{{food.image}}" alt="" height="200px" width="200px"/>
								<div class="agileits-caption">
									<h4>{{food.name}}</h4>
									<p><i class="fa fa-inr"></i> {{food.sale_price}}</p>
								</div>
							</a>
						</div>
					</div>
					<!--{% if forloop.counter0|mod:4 == 0 %}-->
						<!--<div style="height:100px;"></div>-->
					<!--{% endif %}-->

				{% if forloop.counter0|mod:4 == 1 %}
				</div>
				{% endif %}
				{% endfor %}
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //menu -->
	{% include "includes/footer.html" %}